# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "siderolabs/talos"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.2.0"

pre_release = true

preface = """\
"""

[notes]

    [notes.kernel_modules]
        title = "Kernel Modules"
        description = """\
Talos now supports settings kernel module parameters.

Eg:

```yaml
machine:
  kernel:
    modules:
      - name: "br_netfilter"
        parameters:
          - nf_conntrack_max=131072
```
"""

    [notes.sbc]
        title = "Nano Pi R4S"
        description = """\
Talos now supports the Nano Pi R4S SBC.
"""

    [notes.sbc1]
        title = "Raspberry Generic Images"
        description = """\
The Raspberry Pi 4 specific image has been deprecated and will be removed in the v1.4 release of Talos.
Talos now ships a generic Raspberry Pi image that should support more Raspberry Pi variants.
Refer to the docs at https://www.talos.dev/v1.3/talos-guides/install/single-board-computers/rpi_generic/ to find which ones are supported.
"""

    [notes.updates]
        title = "Component Updates"
        description="""\
* Kubernetes: v1.26.0-alpha.2
* Flannel: v0.20.0
* CoreDNS: v1.10.0
* etcd: v3.5.5
* Linux: 5.15.72

Talos is built with Go 1.19.2.
"""

    [notes.etcd]
        title = "etcd Consistency Check"
        description="""\
Talos enables [--experimental-compact-hash-check-enabled](https://github.com/etcd-io/etcd/pull/14120) option by default to improve
etcd store consistency guarantees.

This options is only available with etcd >= v3.5.5, so Talos doesn't support version of etcd before v3.5.5.
"""

    [notes.auditpolicy]
        title = "kube-apiserver Audit Policy"
        description="""\
Talos now supports setting custom audit policy for `kube-apiserver` in the machine configuration.
"""

    [notes.routes]
        title = "Routes"
        description="""\
Talos now supports setting MTU for a specific route.
"""

    [notes.cmdline]
        title = "Kernel Command Line ip= Argument"
        description="""\
Talos now supports referencing interface name via `enxMAC` address notation:

```
ip=172.20.0.2::172.20.0.1:255.255.255.0::enx7085c2dfbc59
```
"""

    [notes.kubespan]
        title = "KubeSpan"
        description="""\
KubeSpan MTU link size is now configurable via `network.kubespan.mtu` setting in the machine configuration.
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/siderolabs/extras"
